vivaldi 2.6.1566.49-20
	* product update ==> 2.6.1566.49
	* added code of conduct
	* pystache: use UTF-8 encoding
	* updated checkvars.sh to v1.0.2
	* updated preinst & postinst
	* product_downloader: support for curl added
	* added helpers.opsifunc v1.4
	* support for 32 bit operating system (testing)
	* delsub_opsiinc completely revised
	* deferring action if running instance is found (no success/error, keep action_request unchanged)
	* update status information for other packages providing the same product on depot
	* updated checkinstance.opsiinc to v1.3 (sub_checkinstance_init, allow kill_override)
	* kill update_notifier.exe independently from kill_running property (issue #1)
	* new property "disable_update_notifier" (issue #2)
	* added feature: local images (according to guideline)
	* variable $PathToExe$ (according to guideline)
	* adjusted log directory for o4i
	* detect testing stage even if package has no matching prefix
	* for distinction: explicit comment in logs for TESTING / RELEASE package
	* for 32 bit compatibility: use %ProgramFiles32Dir% instead of EnvVar("ProgramFiles(x86)")
	* renamed some variables
	* adjusted writing registry values
	* adjusted description in control (en/de)
	* refreshed/completed icon set
	* updated 7zip vo v19.00 x86
	* documentation updated
	* fixed symlink to readme.md

diff --git a/SRC/CLIENT_DATA/product_downloader.sh.in b/SRC/CLIENT_DATA/product_downloader.sh.in
--- a/SRC/CLIENT_DATA/product_downloader.sh.in
+++ b/SRC/CLIENT_DATA/product_downloader.sh.in
@@ -2,8 +2,8 @@
 #=======================================================================
 # Download files from vendor
 #
-# Version 1.3
-# Jens Boettge <boettge@mpi-halle.mpg.de>  2018-05-15 13:59:42 +0200
+# Version 1.4
+# Jens Boettge <boettge@mpi-halle.mpg.de>  2019-07-23 12:51:37 +0200
 #=======================================================================
 # link examples:
 #	https://downloads.vivaldi.com/stable/Vivaldi.1.14.1077.60.exe
@@ -12,12 +12,26 @@
 
 ERR=0
 THIS_DIR=$(dirname $(readlink -f $0))
+DOWNLOADER="curl"
 
-WGET=$(which wget)
-if [ -z "$WGET" ];   then echo "Error: wget not found" ;  exit 200 ; fi
 MD5EXE=$(which md5sum)
-if [ -z "$MD5EXE" ]; then echo "Error: md5sum not found"; exit 201 ; fi
+if [ -z "$MD5EXE" ]; then echo "Error: md5sum not found"; exit 200 ; fi
 
+if [ "$DOWNLOADER" = "wget" ]; then
+	WGET=$(which wget)
+	if [ -z "$WGET" ];   then echo "Error: wget not found" ;  exit 201 ; fi
+	#options for wget:
+	DL_OPTS="--max-redirect=6 --no-cookies -nv "
+	DL_OUT="-O"
+fi
+
+if [ "$DOWNLOADER" = "curl" ]; then
+	CURL=$(which curl)
+	if [ -z "$CURL" ];   then echo "Error: curl not found" ;  exit 202 ; fi
+	#options for curl:
+	DL_OPTS="--silent --show-error -L "
+	DL_OUT="-o"
+fi
 
 if [ -f "${THIS_DIR}/Makefile" ] ; then
 	# Skript is running in the context of building OPSI package via make
@@ -49,11 +63,10 @@ fi
 [ ! -d "${DEST_DIR}" ]  && mkdir ${DEST_DIR}
 # remove trailing "/" in path:
 DEST_DIR=${DEST_DIR%\/}
+
 MD5SUMS="${PROD}.md5sums"
 CNT=0
-WGET_OPTS="--max-redirect=2 --no-cookies "
-FS_THRESHOLD=10000
-
+FS_THRESHOLD=50000
 
 calc_md5()
 {
@@ -100,7 +113,7 @@ download()
         if [ -f "${DEST_DIR}/${PACKAGE}" ]; then
                 echo -e "\tFile already exists"
         else
-                eval wget ${WGET_OPTS} -nv "${DL_URL}" -O "${DEST_DIR}/${PACKAGE}"
+                eval ${DOWNLOADER} ${DL_OPTS} "${DL_URL}" ${DL_OUT} "${DEST_DIR}/${PACKAGE}"
                 if  [ ! -f "${DEST_DIR}/${PACKAGE}" ]; then
                         let "ERR+=1"
                 else
@@ -124,11 +137,26 @@ echo "Timestamp: $(date +'%Y-%m-%d %H:%M:%S')"
 echo "Targtet directory: ${DEST_DIR}"
 echo "=================================================================="
 
+{{#ifdef_use_json_dl}}
+echo "Using download links from spec file."
+declare -A URL=( ["32"]="{{O_DL_EXE_32BIT}}" ["64"]="{{O_DL_EXE_64BIT}}" )
+[ ${#URL[@]} -gt 0 ] && for AX in "${!URL[@]}"; do echo "$AX bit --> ${URL[$AX]}"; done
+{{/ifdef_use_json_dl}}
+{{^ifdef_use_json_dl}}
+echo "Using generated download links"
+declare -A URL=()
+{{/ifdef_use_json_dl}}
+
 CNT=0
-for ARCH in "" ".x64"; do
-		PACKAGE=${PKG_FILE//%%ARCH%%/$ARCH}
-        PKG_URL=${BASE//%%ARCH%%/$ARCH}
-         
+for ARCH in "32" "64"; do
+
+		[ "${ARCH}" == "64" ] && WARCH=".x64" || WARCH=""
+		PACKAGE=${PKG_FILE//%%ARCH%%/$WARCH}
+		if [ ${#URL[@]} -gt 0 ]; then
+			PKG_URL=${URL["${ARCH}"]}
+		else
+			PKG_URL="${BASE//%%ARCH%%/$WARCH}"
+        fi
         download "${PKG_URL}"  "${PACKAGE}"
 done
 
