dfn_vivaldi 1.10.867.42-5 testing:   * new property: desktoplink   * fixed: read properties for custom_post_install/custom_post_uninstall   * files directory will be saved/restored on update   * modified: readme.md   -- J. Boettge <boettge@mpi-halle.mpg.de>  2017-06-27 11:53:28 +0200

diff --git a/OPSI/preinst b/OPSI/preinst
--- a/OPSI/preinst
+++ b/OPSI/preinst
@@ -1,4 +1,4 @@
-#! /bin/sh
+#! /bin/bash
 #===================================================================
 # preinst script for softprod
 # This script executes before that package will be unpacked from its archive file.
@@ -7,30 +7,41 @@
 #   PRODUCT_ID: id of the current product
 #   CLIENT_DATA_DIR: directory where client data will be installed
 #===================================================================
-# J. Boettge <boettge@mpi-halle.mpg.de>  2017-06-26 12:14:55 +0200
+# J. Boettge <boettge@mpi-halle.mpg.de>  2017-06-27 11:50:22 +0200
 #=====================================================================
+
+LOGFILE=/tmp/${PRODUCT_ID}__opsi_package_install.log
+
+exec > $LOGFILE
+exec 2>&1
+chgrp opsiadmin $LOGFILE
+chmod g+rw $LOGFILE
+
+echo "=================================================="
+echo "${PRODUCT_ID} PREINST LOG"
+echo "=================================================="
 
 TMP_DIR=${CLIENT_DATA_DIR}/../${PRODUCT_ID}.tmp
 
 if [ -d $TMP_DIR ]; then
-	echo "Temporary directory $TMP_DIR already exist, aborting!" 1>&2
+	echo "Temporary directory $TMP_DIR already exist, aborting!"
 	exit 1
 fi
 
-[ ! -d $CLIENT_DATA_DIR ] && mkdir $CLIENT_DATA_DIR
+[ ! -d $CLIENT_DATA_DIR ] && exit 0
 mkdir $TMP_DIR
 
-if [ -d $CLIENT_DATA_DIR ]; then
-	echo "Saving previous directories..."
-	for DIRNAME in custom ; do
-		for path in $CLIENT_DATA_DIR/${DIRNAME}; do
-			if [ -e $path ]; then
-				echo "*  moving $path to $TMP_DIR"
-				mv $path $TMP_DIR/ || exit 1
-			fi
-		done
-	done
-fi
+echo "Saving previous directories..."
+for DIRNAME in custom files; do
+	path=$CLIENT_DATA_DIR/${DIRNAME}
+	echo "* [${path}]"
+	if [ -e $path -a ! -h ${path} ]; then
+		echo -e "\tmoving ${path} to ${TMP_DIR}"
+		mv ${path} ${TMP_DIR}/ || exit 2
+	else
+		echo -e "\tdoes not exist or is a symlink"
+	fi
+done
 
 exit 0
 
